### ISSUE TITLE
Mkdocs: Links without trailing `/` can break sidebar navigation

### ISSUE THREAD

**Issue by strugee** [photoprism/photoprism-docs#161]
STR:

1. Visit https://github.com/photoprism/photoprism/blob/e7370838221c373a23dc9a09f186a6065e2a5162/CONTRIBUTING.md#submitting-pull-requests
2. Click the "step-by-step guide" link, which goes to https://docs.photoprism.app/developer-guide/pull-requests
3. Click AFAICT basically anything in the sidebar (I clicked "Build setup")
4. 404 Not Found

Adding a `/` to the URL - e.g. https://docs.photoprism.app/developer-guide/pull-requests/ - makes the sidebar function as intended.

**Comment by lastzero** [comment]
Maybe that's something that must be fixed in [mkdocs material](https://squidfunk.github.io/mkdocs-material/) then?

**Comment by lastzero** [comment]
It seems that this needs to be fixed on the server side or in the CDN config. So I'll have to postpone finding a solution until I have time for doing this.

**Comment by strugee** [comment]
Another option is to do it the quick and dirty way and add a bit of JavaScript to fix up the URL. Doing it server side is better though since that obviously won't work for anyone with JavaScript disabled.

**Comment by lastzero** [comment]
I've tested this again and the problem seems to be fixed with the latest version of MkDocs Material, which we use to render our docs from Markdown files. Shall we close this issue then?

**Comment by strugee** [comment]
Hmm. I can still reproduce using the STR from the description?

**Comment by lastzero** [comment]
You're right, my bad. Didn't properly follow the steps!

**Comment by strugee** [comment]
No problem!

**Comment by graciousgrey** [comment]
This seems to work now. I tested with the exact steps mentioned above and the missing slash has been added automatically.

**Comment by lastzero** [comment]
Since we moved our docs from DigitalOcean to our own server and CDN, this issue seems to be resolved. Feel free to test again!
